// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: whdsl/article/v1/article.proto

package articlev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Article struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MinAmount uint32                 `protobuf:"varint,3,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Article) Reset() {
	*x = Article{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whdsl_article_v1_article_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_whdsl_article_v1_article_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_whdsl_article_v1_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Article) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Article) GetMinAmount() uint32 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *Article) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Article) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ShowTransactionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ShowTransactionsRequest) Reset() {
	*x = ShowTransactionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whdsl_article_v1_article_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowTransactionsRequest) ProtoMessage() {}

func (x *ShowTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whdsl_article_v1_article_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ShowTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_whdsl_article_v1_article_proto_rawDescGZIP(), []int{1}
}

func (x *ShowTransactionsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ShowTransactionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
}

func (x *ShowTransactionsResponse) Reset() {
	*x = ShowTransactionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whdsl_article_v1_article_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowTransactionsResponse) ProtoMessage() {}

func (x *ShowTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whdsl_article_v1_article_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ShowTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_whdsl_article_v1_article_proto_rawDescGZIP(), []int{2}
}

func (x *ShowTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type CalculateAmountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CalculateAmountRequest) Reset() {
	*x = CalculateAmountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whdsl_article_v1_article_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateAmountRequest) ProtoMessage() {}

func (x *CalculateAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whdsl_article_v1_article_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateAmountRequest.ProtoReflect.Descriptor instead.
func (*CalculateAmountRequest) Descriptor() ([]byte, []int) {
	return file_whdsl_article_v1_article_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateAmountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CalculateAmountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount uint32 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *CalculateAmountResponse) Reset() {
	*x = CalculateAmountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whdsl_article_v1_article_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateAmountResponse) ProtoMessage() {}

func (x *CalculateAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whdsl_article_v1_article_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateAmountResponse.ProtoReflect.Descriptor instead.
func (*CalculateAmountResponse) Descriptor() ([]byte, []int) {
	return file_whdsl_article_v1_article_proto_rawDescGZIP(), []int{4}
}

func (x *CalculateAmountResponse) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ShowDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ShowDetailsRequest) Reset() {
	*x = ShowDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whdsl_article_v1_article_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowDetailsRequest) ProtoMessage() {}

func (x *ShowDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whdsl_article_v1_article_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowDetailsRequest.ProtoReflect.Descriptor instead.
func (*ShowDetailsRequest) Descriptor() ([]byte, []int) {
	return file_whdsl_article_v1_article_proto_rawDescGZIP(), []int{5}
}

func (x *ShowDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ShowDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Article *Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
}

func (x *ShowDetailsResponse) Reset() {
	*x = ShowDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whdsl_article_v1_article_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowDetailsResponse) ProtoMessage() {}

func (x *ShowDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whdsl_article_v1_article_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowDetailsResponse.ProtoReflect.Descriptor instead.
func (*ShowDetailsResponse) Descriptor() ([]byte, []int) {
	return file_whdsl_article_v1_article_proto_rawDescGZIP(), []int{6}
}

func (x *ShowDetailsResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type ShowAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShowAllRequest) Reset() {
	*x = ShowAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whdsl_article_v1_article_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowAllRequest) ProtoMessage() {}

func (x *ShowAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whdsl_article_v1_article_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowAllRequest.ProtoReflect.Descriptor instead.
func (*ShowAllRequest) Descriptor() ([]byte, []int) {
	return file_whdsl_article_v1_article_proto_rawDescGZIP(), []int{7}
}

type ShowAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Articles []*Article `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
}

func (x *ShowAllResponse) Reset() {
	*x = ShowAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whdsl_article_v1_article_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowAllResponse) ProtoMessage() {}

func (x *ShowAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whdsl_article_v1_article_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowAllResponse.ProtoReflect.Descriptor instead.
func (*ShowAllResponse) Descriptor() ([]byte, []int) {
	return file_whdsl_article_v1_article_proto_rawDescGZIP(), []int{8}
}

func (x *ShowAllResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

type NewArticleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MinAmount uint32 `protobuf:"varint,2,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
}

func (x *NewArticleRequest) Reset() {
	*x = NewArticleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whdsl_article_v1_article_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewArticleRequest) ProtoMessage() {}

func (x *NewArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whdsl_article_v1_article_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewArticleRequest.ProtoReflect.Descriptor instead.
func (*NewArticleRequest) Descriptor() ([]byte, []int) {
	return file_whdsl_article_v1_article_proto_rawDescGZIP(), []int{9}
}

func (x *NewArticleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewArticleRequest) GetMinAmount() uint32 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

type NewArticleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NewArticleResponse) Reset() {
	*x = NewArticleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whdsl_article_v1_article_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewArticleResponse) ProtoMessage() {}

func (x *NewArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whdsl_article_v1_article_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewArticleResponse.ProtoReflect.Descriptor instead.
func (*NewArticleResponse) Descriptor() ([]byte, []int) {
	return file_whdsl_article_v1_article_proto_rawDescGZIP(), []int{10}
}

func (x *NewArticleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MinAmount uint32 `protobuf:"varint,3,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
}

func (x *UpdateDetailsRequest) Reset() {
	*x = UpdateDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whdsl_article_v1_article_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDetailsRequest) ProtoMessage() {}

func (x *UpdateDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whdsl_article_v1_article_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDetailsRequest.ProtoReflect.Descriptor instead.
func (*UpdateDetailsRequest) Descriptor() ([]byte, []int) {
	return file_whdsl_article_v1_article_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDetailsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDetailsRequest) GetMinAmount() uint32 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

type UpdateDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateDetailsResponse) Reset() {
	*x = UpdateDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whdsl_article_v1_article_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDetailsResponse) ProtoMessage() {}

func (x *UpdateDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whdsl_article_v1_article_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDetailsResponse.ProtoReflect.Descriptor instead.
func (*UpdateDetailsResponse) Descriptor() ([]byte, []int) {
	return file_whdsl_article_v1_article_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateDetailsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveArticleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveArticleRequest) Reset() {
	*x = RemoveArticleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whdsl_article_v1_article_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveArticleRequest) ProtoMessage() {}

func (x *RemoveArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whdsl_article_v1_article_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveArticleRequest.ProtoReflect.Descriptor instead.
func (*RemoveArticleRequest) Descriptor() ([]byte, []int) {
	return file_whdsl_article_v1_article_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveArticleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveArticleResponse) Reset() {
	*x = RemoveArticleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whdsl_article_v1_article_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveArticleResponse) ProtoMessage() {}

func (x *RemoveArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whdsl_article_v1_article_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveArticleResponse.ProtoReflect.Descriptor instead.
func (*RemoveArticleResponse) Descriptor() ([]byte, []int) {
	return file_whdsl_article_v1_article_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveArticleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_whdsl_article_v1_article_proto protoreflect.FileDescriptor

var file_whdsl_article_v1_article_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x77, 0x68, 0x64, 0x73, 0x6c, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2f,
	0x76, 0x31, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x77, 0x68, 0x64, 0x73, 0x6c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e,
	0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x77, 0x68, 0x64, 0x73, 0x6c, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc2, 0x01, 0x0a, 0x07, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x5f, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6d, 0x69, 0x6e,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x29, 0x0a, 0x17,
	0x53, 0x68, 0x6f, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5d, 0x0a, 0x18, 0x53, 0x68, 0x6f, 0x77, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x77, 0x68, 0x64, 0x73,
	0x6c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x28, 0x0a, 0x16, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x31, 0x0a, 0x17, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x24, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x77, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x13, 0x53, 0x68, 0x6f,
	0x77, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x07, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x77, 0x68, 0x64, 0x73, 0x6c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x07, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x77, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x77,
	0x68, 0x64, 0x73, 0x6c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x08, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x73, 0x22, 0x46, 0x0a, 0x11, 0x4e, 0x65, 0x77, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69,
	0x6e, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x6d, 0x69, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x24, 0x0a, 0x12, 0x4e, 0x65, 0x77,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x59, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x69, 0x6e, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x6d, 0x69, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x27, 0x0a, 0x15, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x15, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x32, 0xba, 0x05, 0x0a, 0x0e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x77, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x24, 0x2e, 0x77, 0x68, 0x64, 0x73, 0x6c, 0x2e, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x77,
	0x68, 0x64, 0x73, 0x6c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x68, 0x6f, 0x77, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x07, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x6c, 0x6c,
	0x12, 0x20, 0x2e, 0x77, 0x68, 0x64, 0x73, 0x6c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x77, 0x68, 0x64, 0x73, 0x6c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x23, 0x2e, 0x77, 0x68, 0x64, 0x73, 0x6c, 0x2e, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x77, 0x68, 0x64,
	0x73, 0x6c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65,
	0x77, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x62, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x26, 0x2e, 0x77, 0x68, 0x64, 0x73, 0x6c, 0x2e, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x77, 0x68,
	0x64, 0x73, 0x6c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x26, 0x2e, 0x77, 0x68, 0x64, 0x73, 0x6c, 0x2e,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x27, 0x2e, 0x77, 0x68, 0x64, 0x73, 0x6c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6b, 0x0a, 0x10, 0x53, 0x68,
	0x6f, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x29,
	0x2e, 0x77, 0x68, 0x64, 0x73, 0x6c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x77, 0x68, 0x64, 0x73,
	0x6c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f,
	0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a, 0x0f, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x2e, 0x77, 0x68, 0x64,
	0x73, 0x6c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x77, 0x68, 0x64, 0x73, 0x6c, 0x2e, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0xc4, 0x01, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x68, 0x64, 0x73, 0x6c, 0x2e,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x78, 0x69, 0x68, 0x61, 0x66, 0x65, 0x72,
	0x2f, 0x77, 0x68, 0x64, 0x73, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x77, 0x68,
	0x64, 0x73, 0x6c, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x57, 0x41, 0x58, 0xaa, 0x02,
	0x10, 0x57, 0x68, 0x64, 0x73, 0x6c, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x56,
	0x31, 0xca, 0x02, 0x10, 0x57, 0x68, 0x64, 0x73, 0x6c, 0x5c, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x57, 0x68, 0x64, 0x73, 0x6c, 0x5c, 0x41, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x12, 0x57, 0x68, 0x64, 0x73, 0x6c, 0x3a, 0x3a, 0x41, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_whdsl_article_v1_article_proto_rawDescOnce sync.Once
	file_whdsl_article_v1_article_proto_rawDescData = file_whdsl_article_v1_article_proto_rawDesc
)

func file_whdsl_article_v1_article_proto_rawDescGZIP() []byte {
	file_whdsl_article_v1_article_proto_rawDescOnce.Do(func() {
		file_whdsl_article_v1_article_proto_rawDescData = protoimpl.X.CompressGZIP(file_whdsl_article_v1_article_proto_rawDescData)
	})
	return file_whdsl_article_v1_article_proto_rawDescData
}

var file_whdsl_article_v1_article_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_whdsl_article_v1_article_proto_goTypes = []interface{}{
	(*Article)(nil),                  // 0: whdsl.article.v1.Article
	(*ShowTransactionsRequest)(nil),  // 1: whdsl.article.v1.ShowTransactionsRequest
	(*ShowTransactionsResponse)(nil), // 2: whdsl.article.v1.ShowTransactionsResponse
	(*CalculateAmountRequest)(nil),   // 3: whdsl.article.v1.CalculateAmountRequest
	(*CalculateAmountResponse)(nil),  // 4: whdsl.article.v1.CalculateAmountResponse
	(*ShowDetailsRequest)(nil),       // 5: whdsl.article.v1.ShowDetailsRequest
	(*ShowDetailsResponse)(nil),      // 6: whdsl.article.v1.ShowDetailsResponse
	(*ShowAllRequest)(nil),           // 7: whdsl.article.v1.ShowAllRequest
	(*ShowAllResponse)(nil),          // 8: whdsl.article.v1.ShowAllResponse
	(*NewArticleRequest)(nil),        // 9: whdsl.article.v1.NewArticleRequest
	(*NewArticleResponse)(nil),       // 10: whdsl.article.v1.NewArticleResponse
	(*UpdateDetailsRequest)(nil),     // 11: whdsl.article.v1.UpdateDetailsRequest
	(*UpdateDetailsResponse)(nil),    // 12: whdsl.article.v1.UpdateDetailsResponse
	(*RemoveArticleRequest)(nil),     // 13: whdsl.article.v1.RemoveArticleRequest
	(*RemoveArticleResponse)(nil),    // 14: whdsl.article.v1.RemoveArticleResponse
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
	(*Transaction)(nil),              // 16: whdsl.article.v1.Transaction
}
var file_whdsl_article_v1_article_proto_depIdxs = []int32{
	15, // 0: whdsl.article.v1.Article.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: whdsl.article.v1.Article.updated_at:type_name -> google.protobuf.Timestamp
	16, // 2: whdsl.article.v1.ShowTransactionsResponse.transactions:type_name -> whdsl.article.v1.Transaction
	0,  // 3: whdsl.article.v1.ShowDetailsResponse.article:type_name -> whdsl.article.v1.Article
	0,  // 4: whdsl.article.v1.ShowAllResponse.articles:type_name -> whdsl.article.v1.Article
	5,  // 5: whdsl.article.v1.ArticleService.ShowDetails:input_type -> whdsl.article.v1.ShowDetailsRequest
	7,  // 6: whdsl.article.v1.ArticleService.ShowAll:input_type -> whdsl.article.v1.ShowAllRequest
	9,  // 7: whdsl.article.v1.ArticleService.NewArticle:input_type -> whdsl.article.v1.NewArticleRequest
	11, // 8: whdsl.article.v1.ArticleService.UpdateDetails:input_type -> whdsl.article.v1.UpdateDetailsRequest
	13, // 9: whdsl.article.v1.ArticleService.RemoveArticle:input_type -> whdsl.article.v1.RemoveArticleRequest
	1,  // 10: whdsl.article.v1.ArticleService.ShowTransactions:input_type -> whdsl.article.v1.ShowTransactionsRequest
	3,  // 11: whdsl.article.v1.ArticleService.CalculateAmount:input_type -> whdsl.article.v1.CalculateAmountRequest
	6,  // 12: whdsl.article.v1.ArticleService.ShowDetails:output_type -> whdsl.article.v1.ShowDetailsResponse
	8,  // 13: whdsl.article.v1.ArticleService.ShowAll:output_type -> whdsl.article.v1.ShowAllResponse
	10, // 14: whdsl.article.v1.ArticleService.NewArticle:output_type -> whdsl.article.v1.NewArticleResponse
	12, // 15: whdsl.article.v1.ArticleService.UpdateDetails:output_type -> whdsl.article.v1.UpdateDetailsResponse
	14, // 16: whdsl.article.v1.ArticleService.RemoveArticle:output_type -> whdsl.article.v1.RemoveArticleResponse
	2,  // 17: whdsl.article.v1.ArticleService.ShowTransactions:output_type -> whdsl.article.v1.ShowTransactionsResponse
	4,  // 18: whdsl.article.v1.ArticleService.CalculateAmount:output_type -> whdsl.article.v1.CalculateAmountResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_whdsl_article_v1_article_proto_init() }
func file_whdsl_article_v1_article_proto_init() {
	if File_whdsl_article_v1_article_proto != nil {
		return
	}
	file_whdsl_article_v1_transaction_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_whdsl_article_v1_article_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Article); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whdsl_article_v1_article_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowTransactionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whdsl_article_v1_article_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowTransactionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whdsl_article_v1_article_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateAmountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whdsl_article_v1_article_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateAmountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whdsl_article_v1_article_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whdsl_article_v1_article_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whdsl_article_v1_article_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whdsl_article_v1_article_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whdsl_article_v1_article_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewArticleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whdsl_article_v1_article_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewArticleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whdsl_article_v1_article_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whdsl_article_v1_article_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whdsl_article_v1_article_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveArticleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whdsl_article_v1_article_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveArticleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_whdsl_article_v1_article_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whdsl_article_v1_article_proto_goTypes,
		DependencyIndexes: file_whdsl_article_v1_article_proto_depIdxs,
		MessageInfos:      file_whdsl_article_v1_article_proto_msgTypes,
	}.Build()
	File_whdsl_article_v1_article_proto = out.File
	file_whdsl_article_v1_article_proto_rawDesc = nil
	file_whdsl_article_v1_article_proto_goTypes = nil
	file_whdsl_article_v1_article_proto_depIdxs = nil
}
